import type { Metadata } from "next";
import { League_Spartan, Antonio } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const leagueSpartan = League_Spartan({
  variable: "--font-league-spartan",
  subsets: ["latin"],
});

const antonio = Antonio({
  variable: "--font-antonio",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${leagueSpartan.variable} ${antonio.variable}`}>
      <body
        className={`${leagueSpartan.variable} ${antonio.variable} antialiased`}
      >
        <div className="">
          <Header />
          <hr className="w-full" />
          <main className="">{children}</main>
        </div>
      </body>
    </html>
  );
}
